begin;

create extension if not exists pgtap with schema extensions;

select plan(7);

select has_function(
  'private',
  'rls_auto_enable',
  array[]::text[],
  'private.rls_auto_enable() existe'
);

select hasnt_function(
  'public',
  'rls_auto_enable',
  array[]::text[],
  'public.rls_auto_enable() não existe'
);

select ok(
  exists (
    select 1
    from pg_catalog.pg_event_trigger as event_triggers
    join pg_catalog.pg_proc as functions
      on functions.oid = event_triggers.evtfoid
    join pg_catalog.pg_namespace as namespaces
      on namespaces.oid = functions.pronamespace
    where event_triggers.evtname = 'ensure_rls'
      and event_triggers.evtevent = 'ddl_command_end'
      and namespaces.nspname = 'private'
      and functions.proname = 'rls_auto_enable'
  ),
  'ensure_rls aponta para private.rls_auto_enable()'
);

select ok(
  not exists (
    select 1
    from pg_catalog.pg_proc as functions
    cross join lateral pg_catalog.aclexplode(
      coalesce(
        functions.proacl,
        pg_catalog.acldefault('f', functions.proowner)
      )
    ) as privileges
    where functions.oid = 'private.rls_auto_enable()'::pg_catalog.regprocedure
      and privileges.grantee = 0
      and privileges.privilege_type = 'EXECUTE'
  ),
  'PUBLIC não possui EXECUTE em private.rls_auto_enable()'
);

select ok(
  not pg_catalog.has_function_privilege(
    'anon',
    'private.rls_auto_enable()',
    'EXECUTE'
  ),
  'anon não possui EXECUTE em private.rls_auto_enable()'
);

select ok(
  not pg_catalog.has_function_privilege(
    'authenticated',
    'private.rls_auto_enable()',
    'EXECUTE'
  ),
  'authenticated não possui EXECUTE em private.rls_auto_enable()'
);

create table public.auto_rls_event_trigger_probe (
  id bigint generated by default as identity primary key
);

select ok(
  (
    select relations.relrowsecurity
    from pg_catalog.pg_class as relations
    where relations.oid = 'public.auto_rls_event_trigger_probe'::pg_catalog.regclass
  ),
  'CREATE TABLE em public habilita RLS automaticamente'
);

select * from finish();
rollback;
