import { act, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { GameFlow } from '../draw/GameFlow'
import * as service from './match-service'
import type { FutebolSupabaseClient } from '../lib/supabase/client'
import { group, players } from './test-fixtures'

vi.mock('./match-service', async (original) => ({ ...await original<typeof service>(), saveMatchDraw: vi.fn() }))
const client = {} as FutebolSupabaseClient
const saveMock = vi.mocked(service.saveMatchDraw)
beforeEach(() => { saveMock.mockReset(); saveMock.mockImplementation((_client, id) => Promise.resolve(id)) })
afterEach(() => vi.restoreAllMocks())

async function result(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole('button', { name: 'Selecionar participantes' }))
  await user.click(screen.getByRole('button', { name: 'Selecionar todos' }))
  await user.click(screen.getByRole('button', { name: 'Sortear times' }))
  return screen.findByRole('region', { name: 'Resultado do sorteio' })
}
async function save(user: ReturnType<typeof userEvent.setup>) {
  await user.click(screen.getByRole('button', { name: 'Salvar e aceitar sorteio' }))
  await screen.findByText(/Partida salva e sorteio aceito/)
}

describe('persistência real no fluxo da Fase 7', () => {
  it.each(['owner', 'admin'] as const)('gera UUID antes da chamada e finaliza uma única vez (%s)', async (role) => {
    const user = userEvent.setup(), onSaved = vi.fn()
    const uuid = vi.spyOn(crypto, 'randomUUID')
    saveMock.mockImplementation((_client, id) => { expect(uuid).toHaveBeenCalledOnce(); return Promise.resolve(id) })
    render(<GameFlow client={client} group={{ ...group, role }} players={players} onSaved={onSaved} />)
    await result(user); expect(uuid).not.toHaveBeenCalled()
    await save(user)
    expect(saveMock).toHaveBeenCalledOnce(); expect(onSaved).toHaveBeenCalledWith(uuid.mock.results[0]!.value)
    expect(saveMock.mock.calls[0]![2]).toMatchObject({ group_id: group.id, team_count: 2, players_on_court: 1 })
    expect(screen.queryByRole('button', { name: 'Salvar e aceitar sorteio' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Novo sorteio' })).toBeDisabled()
  })
  it('bloqueia double-submit e mudanças enquanto aguarda resposta', async () => {
    const user = userEvent.setup()
    let resolve!: (id: string) => void
    saveMock.mockImplementation(() => new Promise<string>((r) => { resolve = r }))
    render(<GameFlow client={client} group={group} players={players} />)
    await result(user)
    await user.dblClick(screen.getByRole('button', { name: 'Salvar e aceitar sorteio' }))
    expect(saveMock).toHaveBeenCalledOnce()
    expect(screen.getByRole('button', { name: 'Salvando e aceitando…' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Editar jogo' })).toBeDisabled()
    await act(() => { resolve(saveMock.mock.calls[0]![1]); return Promise.resolve() })
    await screen.findByText(/Partida salva e sorteio aceito/)
  })
  it('retry após rede incerta preserva UUID, conteúdo e snapshots mesmo com mudança no elenco', async () => {
    const user = userEvent.setup(), uuid = vi.spyOn(crypto, 'randomUUID')
    saveMock.mockRejectedValueOnce(new Error('private network detail'))
    const view = render(<GameFlow client={client} group={group} players={players} />)
    await result(user)
    await user.click(screen.getByRole('button', { name: 'Salvar e aceitar sorteio' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('pode já ter sido salva')
    expect(screen.queryByText('private network detail')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Editar jogo' })).toBeDisabled()
    const first = saveMock.mock.calls[0]!
    view.rerender(<GameFlow client={client} group={group} players={[]} />)
    expect(screen.getByText(/P1 · Nível/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Tentar salvar novamente' }))
    await screen.findByText(/Partida salva e sorteio aceito/)
    expect(uuid).toHaveBeenCalledOnce()
    expect(saveMock.mock.calls[1]![1]).toBe(first[1]); expect(saveMock.mock.calls[1]![2]).toBe(first[2])
  })
  it('exige abandono explícito antes de editar conteúdo divergente e usa outro UUID', async () => {
    const user = userEvent.setup(), confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
    saveMock.mockRejectedValueOnce(new Error('timeout'))
    render(<GameFlow client={client} group={group} players={players} />)
    await result(user); await user.click(screen.getByRole('button', { name: 'Salvar e aceitar sorteio' }))
    await screen.findByRole('alert')
    await user.click(screen.getByRole('button', { name: 'Abandonar tentativa e editar' }))
    expect(screen.getByRole('button', { name: 'Editar jogo' })).toBeDisabled()
    confirm.mockReturnValue(true)
    await user.click(screen.getByRole('button', { name: 'Abandonar tentativa e editar' }))
    expect(confirm).toHaveBeenCalledWith(expect.stringContaining('poderá criar outra partida'))
    await user.click(screen.getByRole('button', { name: 'Editar jogo' }))
    await user.type(screen.getByLabelText(/Nome/), 'Partida editada')
    await user.click(screen.getByRole('button', { name: 'Selecionar participantes' }))
    await user.click(screen.getByRole('button', { name: 'Sortear times' }))
    await screen.findByRole('region', { name: 'Resultado do sorteio' }); await save(user)
    expect(saveMock.mock.calls[1]![1]).not.toBe(saveMock.mock.calls[0]![1])
    expect(saveMock.mock.calls[1]![2].name).toBe('Partida editada')
    expect(saveMock.mock.calls[1]![2].draw_runs).toHaveLength(1)
  })
  it('mantém todos rerolls em sequência e exatamente o último aceito', async () => {
    const user = userEvent.setup()
    render(<GameFlow client={client} group={group} players={players} />)
    await result(user)
    for (let i = 0; i < 2; i++) { await user.click(screen.getByRole('button', { name: 'Novo sorteio' })); await waitFor(() => expect(screen.getByRole('button', { name: 'Novo sorteio' })).toBeEnabled()) }
    await save(user)
    const runs = saveMock.mock.calls[0]![2].draw_runs
    expect(runs.map((r) => [r.run_number, r.accepted])).toEqual([[1, false], [2, false], [3, true]])
    expect(new Set(runs.map((r) => r.seed)).size).toBe(3)
  })
  it('descarta os runs anteriores quando a seleção é alterada', async () => {
    const user = userEvent.setup()
    render(<GameFlow client={client} group={group} players={players} />)
    await result(user)
    await user.click(screen.getByRole('button', { name: 'Novo sorteio' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Novo sorteio' })).toBeEnabled())
    await user.click(screen.getByRole('button', { name: 'Voltar aos participantes' }))
    await user.click(screen.getAllByRole('checkbox')[0]!)
    await user.click(screen.getByRole('button', { name: 'Sortear times' }))
    await screen.findByRole('region', { name: 'Resultado do sorteio' }); await save(user)
    expect(saveMock.mock.calls[0]![2].draw_runs).toHaveLength(1)
    expect(saveMock.mock.calls[0]![2].participants).toHaveLength(3)
  })
  it('descarta runs quando a configuração muda, mas preserva ao voltar sem alterações', async () => {
    const user = userEvent.setup()
    render(<GameFlow client={client} group={group} players={players} />)
    await result(user)
    await user.click(screen.getByRole('button', { name: 'Editar jogo' }))
    await user.click(screen.getByRole('button', { name: 'Selecionar participantes' }))
    await user.click(screen.getByRole('button', { name: 'Sortear times' }))
    await screen.findByRole('region', { name: 'Resultado do sorteio' })
    expect(screen.getByText(/2 sorteio\(s\)/)).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Editar jogo' }))
    await user.clear(screen.getByLabelText('Em quadra por time'))
    await user.type(screen.getByLabelText('Em quadra por time'), '2')
    await user.click(screen.getByRole('button', { name: 'Selecionar participantes' }))
    await user.click(screen.getByRole('button', { name: 'Sortear times' }))
    await screen.findByRole('region', { name: 'Resultado do sorteio' }); await save(user)
    expect(saveMock.mock.calls[0]![2].draw_runs).toHaveLength(1)
    expect(saveMock.mock.calls[0]![2].assignments.every((a) => !a.starts_as_reserve)).toBe(true)
  })
  it('persiste a troca manual final, mantendo seed/version do draw-base', async () => {
    const user = userEvent.setup()
    render(<GameFlow client={client} group={group} players={players} />)
    const region = await result(user)
    await user.click(within(region).getAllByRole('button', { name: 'Selecionar para ajuste' })[0]!)
    await user.click(within(region).getAllByRole('button', { name: 'Trocar com selecionado' })[0]!)
    await save(user)
    expect(saveMock.mock.calls[0]![2].assignments.filter((a) => a.assignment_source === 'manual')).toHaveLength(2)
    expect(saveMock.mock.calls[0]![2].draw_runs[0]).toMatchObject({ accepted: true, algorithm_version: 'balanced-candidates-v1' })
  })
  it('invalida resultado quando níveis/goleiros do elenco mudam antes de salvar', async () => {
    const user = userEvent.setup()
    const view = render(<GameFlow client={client} group={group} players={players} />)
    await result(user)
    view.rerender(<GameFlow client={client} group={group} players={players.map((p) => ({ ...p, skill_rating: 1 }))} />)
    expect(screen.queryByRole('button', { name: 'Salvar e aceitar sorteio' })).not.toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Revisar participantes' }))
    await user.click(screen.getByRole('button', { name: 'Sortear times' }))
    await screen.findByRole('region', { name: 'Resultado do sorteio' }); await save(user)
    expect(saveMock.mock.calls[0]![2].draw_runs).toHaveLength(1)
    expect(saveMock.mock.calls[0]![2].participants.every((p) => p.skill_rating_snapshot === 1)).toBe(true)
  })
})
